services:
  db:
    image: postgres:16-alpine
    container_name: expensevoice_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: expensevoice
    ports:
      - "5432:5432"
    volumes:
      - expensevoice_pg:/var/lib/postgresql/data

volumes:
  expensevoice_pg:
